version: '3'

services:
    httpd:
        container_name: "${PROJECT_NAME}_httpd_1"
        image: httpd:2.4.25
        restart: always
        environment:
            - APACHE_LOG_DIR=/usr/local/apache2/logs
        ports:
            - "${HTTP_PORT}:80"
        volumes:
            - ${DOCKER_STACK_DIR}/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ${DOCKER_STACK_DIR}/apache/vhosts/:/usr/local/apache2/conf/vhosts
            - ${ROOT_DIR}/www:/var/www
        links:
            - php
        depends_on:
            - php

    php:
        container_name: "${PROJECT_NAME}_php_1"
        image: noveni/php-ovh:7.2
        restart: always
        volumes:
            - ${ROOT_DIR}/www:/var/www
        expose:
            - 9000
        depends_on:
            - db
        links:
            - db

    db:
        container_name: "${PROJECT_NAME}_mysql_1"
        image: mysql:5.6.36
        restart: always
        expose:
            - 3306
        volumes:
            - ${DOCKER_STACK_DIR}/_dockerdb/:/docker-entrypoint-initdb.d
            - ${DOCKER_STACK_DIR}/mysql:/etc/mysql/conf.d
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

    phpmyadmin:
        container_name: "${PROJECT_NAME}_phpmyadmin_1"
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        ports:
            - "${PHPMYADMIN_PORT}:80"
        links:
            - db
        depends_on:
            - db

    node:
        container_name: "${PROJECT_NAME}_node_1"
        image: node:latest
        volumes:
            - ${ROOT_DIR}/www:/var/www
        working_dir: /var/www
        ports:
            - ${NODE_PORT}:3000
        depends_on:
            - php
        links:
            - php
volumes:
    dbdata: